version: "3.9"

services:

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: f4_el
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      CELERY_BROKER_HOST: redis
      DB_HOST: db
      DB_NAME: postgres
    depends_on:
        - redis
        - db
    volumes:
      - ./alembic:/app/alembic
      - ./celery_home:/app/celery_home
      - ./media:/app/media
      - ./src:/app/src
      - ./static:/app/static
      - ./alembic.ini:/app/alembic.ini
    command: ["sh", "-c", "poetry run alembic upgrade head &&
                                              PYTHONPATH=/app poetry run python src/scripts/create_default_superuser.py && 
                                              poetry run uvicorn src.main:app --host 0.0.0.0 --reload"]
    
  celery-worker:
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - ./celery_home:/app/celery_home
      - ./media:/app/media
      - ./src:/app/src
      - ./static:/app/static
    environment:
      CELERY_BROKER_HOST: redis
    command: ["sh", "-c", "poetry run celery -A celery_home.config.app_celery worker --loglevel=info"]

  celery-beat:
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - ./celery_home:/app/celery_home
      - ./media:/app/media
      - ./src:/app/src
      - ./static:/app/static
    environment:
      CELERY_BROKER_HOST: redis
    command: ["sh", "-c", "poetry run celery -A celery_home.config.app_celery beat --loglevel=info"]

  flower:
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_HOST: redis
    command: ["sh", "-c", "poetry run celery -A celery_home.config.app_celery flower"]

volumes:
  postgres_data:
