"""product, rubric, association tables added

Revision ID: c1762e9cad52
Revises: 234875972e6b
Create Date: 2025-04-16 11:15:46.500728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1762e9cad52'
down_revision: Union[str, None] = '234875972e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_el_rubric_product_association_product_id_el_product', 'el_rubric_product_association', type_='foreignkey')
    op.drop_constraint('fk_el_rubric_product_association_rubric_id_el_rubric', 'el_rubric_product_association', type_='foreignkey')
    op.create_foreign_key(op.f('fk_el_rubric_product_association_product_id_el_product'), 'el_rubric_product_association', 'el_product', ['product_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk_el_rubric_product_association_rubric_id_el_rubric'), 'el_rubric_product_association', 'el_rubric', ['rubric_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_el_rubric_product_association_rubric_id_el_rubric'), 'el_rubric_product_association', type_='foreignkey')
    op.drop_constraint(op.f('fk_el_rubric_product_association_product_id_el_product'), 'el_rubric_product_association', type_='foreignkey')
    op.create_foreign_key('fk_el_rubric_product_association_rubric_id_el_rubric', 'el_rubric_product_association', 'el_rubric', ['rubric_id'], ['id'])
    op.create_foreign_key('fk_el_rubric_product_association_product_id_el_product', 'el_rubric_product_association', 'el_product', ['product_id'], ['id'])
    # ### end Alembic commands ###
