"""product, rubric, association tables added

Revision ID: 1aa469498982
Revises: 3011b269d1cb
Create Date: 2025-04-14 18:50:18.668345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa469498982'
down_revision: Union[str, None] = '3011b269d1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_rubric',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.CheckConstraint('length(title) >= 3', name=op.f('ck_el_brand_check_title_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_rubric')),
    sa.UniqueConstraint('title', name=op.f('uq_el_rubric_title'))
    )
    op.create_table('el_product',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.CheckConstraint('length(title) >= 3', name=op.f('ck_el_brand_check_title_min_length')),
    sa.ForeignKeyConstraint(['brand_id'], ['el_brand.id'], name=op.f('fk_el_product_brand_id_el_brand'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_product')),
    sa.UniqueConstraint('title', name=op.f('uq_el_product_title'))
    )
    op.create_table('el_rubric_image',
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['el_rubric.id'], name=op.f('fk_el_rubric_image_rubric_id_el_rubric'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_rubric_image')),
    sa.UniqueConstraint('rubric_id', name=op.f('uq_el_rubric_image_rubric_id'))
    )
    op.create_table('el_product_image',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_product_image_product_id_el_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_product_image'))
    )
    op.create_table('el_rubric_product_association',
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_rubric_product_association_product_id_el_product')),
    sa.ForeignKeyConstraint(['rubric_id'], ['el_rubric.id'], name=op.f('fk_el_rubric_product_association_rubric_id_el_rubric')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_rubric_product_association')),
    sa.UniqueConstraint('rubric_id', 'product_id', name='idx_unique_rubric_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_rubric_product_association')
    op.drop_table('el_product_image')
    op.drop_table('el_rubric_image')
    op.drop_table('el_product')
    op.drop_table('el_rubric')
    # ### end Alembic commands ###
