"""votes table changed

Revision ID: 9939ae9370ad
Revises: 7800c8bba138
Create Date: 2025-04-22 17:27:10.531885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9939ae9370ad'
down_revision: Union[str, None] = '7800c8bba138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('el_vote', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_el_vote_user_id_el_user', 'el_vote', type_='foreignkey')
    op.create_foreign_key(op.f('fk_el_vote_user_id_el_user'), 'el_vote', 'el_user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_el_vote_user_id_el_user'), 'el_vote', type_='foreignkey')
    op.create_foreign_key('fk_el_vote_user_id_el_user', 'el_vote', 'el_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('el_vote', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
