"""votes table added

Revision ID: 7800c8bba138
Revises: 07e056eb3bc9
Create Date: 2025-04-22 17:13:36.450035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7800c8bba138'
down_revision: Union[str, None] = '07e056eb3bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_vote',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(name) > 2', name=op.f('ck_el_vote_check_name_min_length')),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_vote_product_id_el_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_vote_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_vote'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_vote')
    # ### end Alembic commands ###
