"""changed total_price to total_cost

Revision ID: 30853b1d7021
Revises: 217383e17310
Create Date: 2025-05-08 16:46:16.684239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30853b1d7021'
down_revision: Union[str, None] = '217383e17310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('el_order', sa.Column('total_cost', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.drop_column('el_order', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('el_order', sa.Column('total_price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False))
    op.drop_column('el_order', 'total_cost')
    # ### end Alembic commands ###
