"""add table Posts

Revision ID: 0bd1a9aa44ae
Revises: ba6172be682f
Create Date: 2025-04-25 14:02:01.013507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd1a9aa44ae'
down_revision: Union[str, None] = 'ba6172be682f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_post',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), server_default='Anonymous', nullable=False),
    sa.Column('review', sa.String(length=1000), server_default='review', nullable=False),
    sa.Column('published', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(name) <= 75', name=op.f('ck_el_post_check_name_max_length')),
    sa.CheckConstraint('length(name) > 2', name=op.f('ck_el_post_check_name_min_length')),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_post_product_id_el_product'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_post_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_post'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_post')
    # ### end Alembic commands ###
