"""brand, brandimage tables added

Revision ID: 3011b269d1cb
Revises: d0a6781d3ffc
Create Date: 2025-04-14 11:58:36.754580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3011b269d1cb'
down_revision: Union[str, None] = 'd0a6781d3ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_brand',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.CheckConstraint('length(title) >= 3', name=op.f('ck_el_brand_check_title_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_brand')),
    sa.UniqueConstraint('title', name=op.f('uq_el_brand_title'))
    )
    op.create_table('el_brand_image',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['el_brand.id'], name=op.f('fk_el_brand_image_brand_id_el_brand'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_brand_image')),
    sa.UniqueConstraint('brand_id', name=op.f('uq_el_brand_image_brand_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_brand_image')
    op.drop_table('el_brand')
    # ### end Alembic commands ###
