"""sale_information table added

Revision ID: 07e056eb3bc9
Revises: a7c9a25a5689
Create Date: 2025-04-18 16:30:44.308766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e056eb3bc9'
down_revision: Union[str, None] = 'a7c9a25a5689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_sale_information',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('voted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('viewed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_summary', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.CheckConstraint('rating <= 5', name=op.f('ck_el_sale_information_check_rating_max_value')),
    sa.CheckConstraint('rating >= 0', name=op.f('ck_el_sale_information_check_rating_min_value')),
    sa.CheckConstraint('rating_summary >= 0', name=op.f('ck_el_sale_information_check_rating_summary_min_value')),
    sa.CheckConstraint('sold_count >= 0', name=op.f('ck_el_sale_information_check_sold_count_min_value')),
    sa.CheckConstraint('viewed_count >= 0', name=op.f('ck_el_sale_information_check_viewed_count_min_value')),
    sa.CheckConstraint('voted_count >= 0', name=op.f('ck_el_sale_information_check_voted_count_min_value')),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_sale_information_product_id_el_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_el_sale_information'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_sale_information')
    # ### end Alembic commands ###
