"""additional_information table added

Revision ID: a7c9a25a5689
Revises: c1762e9cad52
Create Date: 2025-04-18 10:05:42.249847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c9a25a5689'
down_revision: Union[str, None] = 'c1762e9cad52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_additional_information',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('guarantee', sa.String(), nullable=True),
    sa.CheckConstraint('weight > 0', name=op.f('ck_el_additional_information_check_weight_min_value')),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_additional_information_product_id_el_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_el_additional_information'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_additional_information')
    # ### end Alembic commands ###
