"""add tables Cart, CartItems

Revision ID: 66437b18830e
Revises: 0bd1a9aa44ae
Create Date: 2025-04-26 11:14:27.705253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66437b18830e'
down_revision: Union[str, None] = '0bd1a9aa44ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_cart_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_el_cart'))
    )
    op.create_table('el_cart_item',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_el_cart_item_check_quantity_min_value')),
    sa.ForeignKeyConstraint(['cart_id'], ['el_cart.user_id'], name=op.f('fk_el_cart_item_cart_id_el_cart'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['el_product.id'], name=op.f('fk_el_cart_item_product_id_el_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_cart_item')),
    sa.UniqueConstraint('product_id', 'cart_id', name='cart_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_cart_item')
    op.drop_table('el_cart')
    # ### end Alembic commands ###
