"""changed addresses constraints

Revision ID: 217383e17310
Revises: a5836b4db948
Create Date: 2025-05-07 16:22:45.875123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217383e17310'
down_revision: Union[str, None] = 'a5836b4db948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('el_address', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.drop_index('ix_el_address_email', table_name='el_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_el_address_email', 'el_address', ['email'], unique=True)
    op.alter_column('el_address', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
