"""create users table

Revision ID: d0a6781d3ffc
Revises: a4d1712a76a4
Create Date: 2025-04-07 18:50:06.831241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a6781d3ffc'
down_revision: Union[str, None] = 'a4d1712a76a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_user',
    sa.Column('firstname', sa.String(length=50), server_default='John', nullable=True),
    sa.Column('lastname', sa.String(length=50), server_default='Doe', nullable=True),
    sa.Column('data_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_el_user'))
    )
    op.create_index(op.f('ix_el_user_email'), 'el_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_el_user_email'), table_name='el_user')
    op.drop_table('el_user')
    # ### end Alembic commands ###
