"""add tables orders, persons, addresses

Revision ID: a5836b4db948
Revises: 66437b18830e
Create Date: 2025-05-06 12:31:53.020460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5836b4db948'
down_revision: Union[str, None] = '66437b18830e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_address',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phonenumber', sa.String(length=20), nullable=False),
    sa.CheckConstraint('length(address) > 5', name=op.f('ck_el_address_check_address_min_length')),
    sa.CheckConstraint('length(city) > 1', name=op.f('ck_el_address_check_city_min_length')),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_address_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_el_address'))
    )
    op.create_index(op.f('ix_el_address_email'), 'el_address', ['email'], unique=True)
    op.create_table('el_order',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phonenumber', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('order_content', sa.JSON(), nullable=False),
    sa.Column('person_content', sa.JSON(), nullable=False),
    sa.Column('address_content', sa.JSON(), nullable=False),
    sa.Column('time_placed', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_delivered', sa.DateTime(), nullable=True),
    sa.Column('move_to', sa.Integer(), nullable=False),
    sa.Column('payment_conditions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_order_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id', name=op.f('pk_el_order'))
    )
    op.create_table('el_person',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.CheckConstraint('length(company_name) > 1', name=op.f('ck_el_person_check_company_name_min_length')),
    sa.CheckConstraint('length(firstname) > 1', name=op.f('ck_el_person_check_name_min_length')),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_person_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_el_person'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_person')
    op.drop_table('el_order')
    op.drop_index(op.f('ix_el_address_email'), table_name='el_address')
    op.drop_table('el_address')
    # ### end Alembic commands ###
