"""usertools table added

Revision ID: ba6172be682f
Revises: 596611c4b8fc
Create Date: 2025-04-24 12:16:41.377433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6172be682f'
down_revision: Union[str, None] = '596611c4b8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('el_user_tools',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_length_rv', sa.Integer(), server_default='8', nullable=False),
    sa.Column('max_length_w', sa.Integer(), server_default='8', nullable=False),
    sa.Column('max_length_c', sa.Integer(), server_default='4', nullable=False),
    sa.Column('recently_viewed', sa.JSON(), nullable=False),
    sa.Column('wishlist', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.CheckConstraint('max_length_c > 0', name=op.f('ck_el_user_tools_check_c_min_value')),
    sa.CheckConstraint('max_length_rv > 0', name=op.f('ck_el_user_tools_check_rv_min_value')),
    sa.CheckConstraint('max_length_w > 0', name=op.f('ck_el_user_tools_check_w_min_value')),
    sa.ForeignKeyConstraint(['user_id'], ['el_user.id'], name=op.f('fk_el_user_tools_user_id_el_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_el_user_tools'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('el_user_tools')
    # ### end Alembic commands ###
